=== J0seph-Mart1n/WTL-Practical/WT Assignment 3/employees.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT employees (department+)>
<!ELEMENT department (name, emp_id, age, salary)>
<!ELEMENT name (#PCDATA)> 
<!ELEMENT emp_id (#PCDATA)> 
<!ELEMENT age (#PCDATA)> 
<!ELEMENT salary (#PCDATA)>

=== J0seph-Mart1n/WTL-Practical/WT Assignment 3/employees2.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="employees.xsl" ?>
<!-- <!DOCTYPE employees SYSTEM "employees.dtd"> -->

<employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="employees.xsd">
    <department>
        <name>Joseph Martin</name>
        <emp_id>123</emp_id>
        <age>20</age>
        <salary>100000</salary>
    </department>
    <department>
        <name>Akash</name>
        <emp_id>45</emp_id>
        <age>21</age>
        <salary>120000</salary>
    </department>
    <department>
        <name>Akshay</name>
        <emp_id>121</emp_id>
        <age>23</age>
        <salary>12300</salary>
    </department>
</employees>
